# Generated by Django 3.2.5 on 2022-08-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit', 'Can modify available list of authors'),)},
        ),
    ]
