# Generated by Django 3.2.5 on 2022-08-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit_authors', 'Can modify available list of authors'),)},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned_books', 'Can set book as returned'), ('can_view_all_books', 'Can view all available book instances'))},
        ),
    ]
