# Generated by Django 3.2.5 on 2022-08-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220809_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_edit_books', 'Can edit available books'),)},
        ),
    ]
