# Generated by Django 3.2.5 on 2022-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='author',
            name='dod',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
    ]
